---
- name: Install NFS
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nfs-kernel-server

# http://docs.ansible.com/ansible/latest/modules/file_module.html
- name: mkdir /var/nfs/general
  file:
    path: /var/nfs/general
    owner: nobody
    group: nogroup
    state: directory

- name: Create NFS configuration file
  template: src=exports dest=/etc/exports backup=yes
  notify:
  - restart nfs-kernel-server

- name: Start NFS Service
  service: name=nfs-kernel-server state=started enabled=yes
