---
- name: Install bind9 and dnsutils
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - bind9
    - dnsutils

- name: Create configuration file
  template: src=db.cuc.edu.cn dest=/etc/bind/db.cuc.edu.cn backup=yes

- name: Create configuration file
  template: src=named.conf.local dest=/etc/bind/named.conf.local backup=yes
  notify:
  - restart bind9

- name: Start DNS Service
  service: name=bind9 state=started enabled=yes
